# Generated by Django 4.2.2 on 2023-06-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('book_title', models.CharField(max_length=500)),
                ('book_writer', models.CharField(max_length=50)),
                ('book_publish', models.CharField(max_length=100)),
                ('book_class', models.IntegerField()),
            ],
            options={
                'db_table': 'booktbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommand_id', models.IntegerField()),
                ('recommand_gender', models.CharField(max_length=5)),
                ('recommand_age', models.CharField(max_length=20)),
                ('recommand_class', models.IntegerField()),
                ('recommand_class_cnt', models.IntegerField()),
            ],
            options={
                'db_table': 'recommandtbl',
                'managed': False,
            },
        ),
    ]
